### ISSUE TITLE
v2: Not all tests are executed on macOS

### ISSUE THREAD

**Issue by ash2k** [grpc-ecosystem/go-grpc-middleware#411]
https://github.com/grpc-ecosystem/go-grpc-middleware/runs/2203038390?check_suite_focus=true#step:5:6

There is an issue in the makefile.

**Comment by yashrsharma44** [comment]
This issue has been addressed by #413 so closing.
Let me know if this needs to be opened :)

**Comment by ash2k** [comment]
I'm sorry, but it was not addressed - I was not fixing it. It's still happening e.g. https://github.com/grpc-ecosystem/go-grpc-middleware/runs/1895406088?check_suite_focus=true#step:5:7

**Comment by ash2k** [comment]
Ok, here is a recent test run https://github.com/grpc-ecosystem/go-grpc-middleware/runs/2436081775?check_suite_focus=true#step:5:6

**Comment by bwplotka** [comment]
We can't see logs (too old) ): Let's make sure to paste exact problem next time.

**Comment by aboryslawski** [comment]
All tests pass for both `make test` and `go test ./...` for me locally. Apple M1 Pro macOS 13.6 (22G120).

**Comment by aboryslawski** [comment]
Unless @ash2k is referring to some specific tests that are omitted.

**Comment by ash2k** [comment]
Well, I don't remember what the problem was.
